// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: plugins/proto/storage.proto

package storagepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BackendConfigProto carries the serialised BackendConfig for Connect calls.
//
// Note: the BackendConfig.Warning field is loader-side only and is NOT
// transmitted to the plugin binary — it is populated by the loader after
// Connect returns, never by the plugin itself.
type BackendConfigProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Enabled       bool                   `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty"`
	AutoSync      bool                   `protobuf:"varint,5,opt,name=auto_sync,json=autoSync,proto3" json:"auto_sync,omitempty"`
	Params        map[string]string      `protobuf:"bytes,6,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	SyncDir       string                 `protobuf:"bytes,7,opt,name=sync_dir,json=syncDir,proto3" json:"sync_dir,omitempty"`
	RemotePath    string                 `protobuf:"bytes,8,opt,name=remote_path,json=remotePath,proto3" json:"remote_path,omitempty"`
	LocalPath     string                 `protobuf:"bytes,9,opt,name=local_path,json=localPath,proto3" json:"local_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackendConfigProto) Reset() {
	*x = BackendConfigProto{}
	mi := &file_plugins_proto_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackendConfigProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackendConfigProto) ProtoMessage() {}

func (x *BackendConfigProto) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_proto_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackendConfigProto.ProtoReflect.Descriptor instead.
func (*BackendConfigProto) Descriptor() ([]byte, []int) {
	return file_plugins_proto_storage_proto_rawDescGZIP(), []int{0}
}

func (x *BackendConfigProto) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BackendConfigProto) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BackendConfigProto) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *BackendConfigProto) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *BackendConfigProto) GetAutoSync() bool {
	if x != nil {
		return x.AutoSync
	}
	return false
}

func (x *BackendConfigProto) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *BackendConfigProto) GetSyncDir() string {
	if x != nil {
		return x.SyncDir
	}
	return ""
}

func (x *BackendConfigProto) GetRemotePath() string {
	if x != nil {
		return x.RemotePath
	}
	return ""
}

func (x *BackendConfigProto) GetLocalPath() string {
	if x != nil {
		return x.LocalPath
	}
	return ""
}

// FileInfoProto carries metadata for a remote file or directory.
type FileInfoProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	IsDir         bool                   `protobuf:"varint,4,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	ModTimeUnix   int64                  `protobuf:"varint,5,opt,name=mod_time_unix,json=modTimeUnix,proto3" json:"mod_time_unix,omitempty"` // Unix timestamp (seconds)
	Etag          string                 `protobuf:"bytes,6,opt,name=etag,proto3" json:"etag,omitempty"`
	IsPlaceholder bool                   `protobuf:"varint,7,opt,name=is_placeholder,json=isPlaceholder,proto3" json:"is_placeholder,omitempty"`
	IsCached      bool                   `protobuf:"varint,8,opt,name=is_cached,json=isCached,proto3" json:"is_cached,omitempty"`
	Version       string                 `protobuf:"bytes,20,opt,name=version,proto3" json:"version,omitempty"` // opaque version token (#131): ETag for WebDAV, ctime decimal for MooseFS, "" otherwise
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileInfoProto) Reset() {
	*x = FileInfoProto{}
	mi := &file_plugins_proto_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInfoProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfoProto) ProtoMessage() {}

func (x *FileInfoProto) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_proto_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfoProto.ProtoReflect.Descriptor instead.
func (*FileInfoProto) Descriptor() ([]byte, []int) {
	return file_plugins_proto_storage_proto_rawDescGZIP(), []int{1}
}

func (x *FileInfoProto) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileInfoProto) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileInfoProto) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileInfoProto) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

func (x *FileInfoProto) GetModTimeUnix() int64 {
	if x != nil {
		return x.ModTimeUnix
	}
	return 0
}

func (x *FileInfoProto) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

func (x *FileInfoProto) GetIsPlaceholder() bool {
	if x != nil {
		return x.IsPlaceholder
	}
	return false
}

func (x *FileInfoProto) GetIsCached() bool {
	if x != nil {
		return x.IsCached
	}
	return false
}

func (x *FileInfoProto) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// FileEventProto carries a change notification from Watch.
type FileEventProto struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	EventType           string                 `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"` // "created" | "modified" | "deleted" | "renamed" | "metadata_changed"
	Path                string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	OldPath             string                 `protobuf:"bytes,3,opt,name=old_path,json=oldPath,proto3" json:"old_path,omitempty"`
	TimestampUnix       int64                  `protobuf:"varint,4,opt,name=timestamp_unix,json=timestampUnix,proto3" json:"timestamp_unix,omitempty"`
	Source              string                 `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`                                                           // "local" | "remote"
	ModTimeUnix         int64                  `protobuf:"varint,6,opt,name=mod_time_unix,json=modTimeUnix,proto3" json:"mod_time_unix,omitempty"`                           // file's new modtime at detection time; 0 when unavailable (#130)
	PreviousModTimeUnix int64                  `protobuf:"varint,7,opt,name=previous_mod_time_unix,json=previousModTimeUnix,proto3" json:"previous_mod_time_unix,omitempty"` // file's previous modtime; 0 when unknown/created (#130)
	MetadataOnly        bool                   `protobuf:"varint,8,opt,name=metadata_only,json=metadataOnly,proto3" json:"metadata_only,omitempty"`                          // true when only metadata changed, size stable (#130)
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *FileEventProto) Reset() {
	*x = FileEventProto{}
	mi := &file_plugins_proto_storage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileEventProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileEventProto) ProtoMessage() {}

func (x *FileEventProto) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_proto_storage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileEventProto.ProtoReflect.Descriptor instead.
func (*FileEventProto) Descriptor() ([]byte, []int) {
	return file_plugins_proto_storage_proto_rawDescGZIP(), []int{2}
}

func (x *FileEventProto) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *FileEventProto) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileEventProto) GetOldPath() string {
	if x != nil {
		return x.OldPath
	}
	return ""
}

func (x *FileEventProto) GetTimestampUnix() int64 {
	if x != nil {
		return x.TimestampUnix
	}
	return 0
}

func (x *FileEventProto) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *FileEventProto) GetModTimeUnix() int64 {
	if x != nil {
		return x.ModTimeUnix
	}
	return 0
}

func (x *FileEventProto) GetPreviousModTimeUnix() int64 {
	if x != nil {
		return x.PreviousModTimeUnix
	}
	return 0
}

func (x *FileEventProto) GetMetadataOnly() bool {
	if x != nil {
		return x.MetadataOnly
	}
	return false
}

// UploadChunk is sent by the client during an Upload RPC.
// The first message must contain the metadata fields; subsequent messages
// carry data only (metadata fields are ignored after the first message).
type UploadChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Metadata — populated in first message only.
	LocalPath  string `protobuf:"bytes,1,opt,name=local_path,json=localPath,proto3" json:"local_path,omitempty"`
	RemotePath string `protobuf:"bytes,2,opt,name=remote_path,json=remotePath,proto3" json:"remote_path,omitempty"`
	TotalBytes int64  `protobuf:"varint,3,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"` // used by server to compute progress
	// Payload — present in every message.
	Data          []byte `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadChunk) Reset() {
	*x = UploadChunk{}
	mi := &file_plugins_proto_storage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadChunk) ProtoMessage() {}

func (x *UploadChunk) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_proto_storage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadChunk.ProtoReflect.Descriptor instead.
func (*UploadChunk) Descriptor() ([]byte, []int) {
	return file_plugins_proto_storage_proto_rawDescGZIP(), []int{3}
}

func (x *UploadChunk) GetLocalPath() string {
	if x != nil {
		return x.LocalPath
	}
	return ""
}

func (x *UploadChunk) GetRemotePath() string {
	if x != nil {
		return x.RemotePath
	}
	return ""
}

func (x *UploadChunk) GetTotalBytes() int64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *UploadChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// UploadResult is returned by the server after the last chunk is received.
type UploadResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"` // empty on success
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadResult) Reset() {
	*x = UploadResult{}
	mi := &file_plugins_proto_storage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadResult) ProtoMessage() {}

func (x *UploadResult) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_proto_storage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadResult.ProtoReflect.Descriptor instead.
func (*UploadResult) Descriptor() ([]byte, []int) {
	return file_plugins_proto_storage_proto_rawDescGZIP(), []int{4}
}

func (x *UploadResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// DownloadRequest initiates a Download RPC.
type DownloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RemotePath    string                 `protobuf:"bytes,1,opt,name=remote_path,json=remotePath,proto3" json:"remote_path,omitempty"`
	LocalPath     string                 `protobuf:"bytes,2,opt,name=local_path,json=localPath,proto3" json:"local_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadRequest) Reset() {
	*x = DownloadRequest{}
	mi := &file_plugins_proto_storage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadRequest) ProtoMessage() {}

func (x *DownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_proto_storage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadRequest.ProtoReflect.Descriptor instead.
func (*DownloadRequest) Descriptor() ([]byte, []int) {
	return file_plugins_proto_storage_proto_rawDescGZIP(), []int{5}
}

func (x *DownloadRequest) GetRemotePath() string {
	if x != nil {
		return x.RemotePath
	}
	return ""
}

func (x *DownloadRequest) GetLocalPath() string {
	if x != nil {
		return x.LocalPath
	}
	return ""
}

// DownloadChunk is streamed by the server during a Download RPC.
type DownloadChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	BytesDone     int64                  `protobuf:"varint,2,opt,name=bytes_done,json=bytesDone,proto3" json:"bytes_done,omitempty"`
	BytesTotal    int64                  `protobuf:"varint,3,opt,name=bytes_total,json=bytesTotal,proto3" json:"bytes_total,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"` // non-empty on terminal error
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadChunk) Reset() {
	*x = DownloadChunk{}
	mi := &file_plugins_proto_storage_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadChunk) ProtoMessage() {}

func (x *DownloadChunk) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_proto_storage_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadChunk.ProtoReflect.Descriptor instead.
func (*DownloadChunk) Descriptor() ([]byte, []int) {
	return file_plugins_proto_storage_proto_rawDescGZIP(), []int{6}
}

func (x *DownloadChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *DownloadChunk) GetBytesDone() int64 {
	if x != nil {
		return x.BytesDone
	}
	return 0
}

func (x *DownloadChunk) GetBytesTotal() int64 {
	if x != nil {
		return x.BytesTotal
	}
	return 0
}

func (x *DownloadChunk) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type NameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NameRequest) Reset() {
	*x = NameRequest{}
	mi := &file_plugins_proto_storage_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NameRequest) ProtoMessage() {}

func (x *NameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_proto_storage_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NameRequest.ProtoReflect.Descriptor instead.
func (*NameRequest) Descriptor() ([]byte, []int) {
	return file_plugins_proto_storage_proto_rawDescGZIP(), []int{7}
}

type NameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NameResponse) Reset() {
	*x = NameResponse{}
	mi := &file_plugins_proto_storage_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NameResponse) ProtoMessage() {}

func (x *NameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_proto_storage_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NameResponse.ProtoReflect.Descriptor instead.
func (*NameResponse) Descriptor() ([]byte, []int) {
	return file_plugins_proto_storage_proto_rawDescGZIP(), []int{8}
}

func (x *NameResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ConnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *BackendConfigProto    `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectRequest) Reset() {
	*x = ConnectRequest{}
	mi := &file_plugins_proto_storage_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectRequest) ProtoMessage() {}

func (x *ConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_proto_storage_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectRequest.ProtoReflect.Descriptor instead.
func (*ConnectRequest) Descriptor() ([]byte, []int) {
	return file_plugins_proto_storage_proto_rawDescGZIP(), []int{9}
}

func (x *ConnectRequest) GetConfig() *BackendConfigProto {
	if x != nil {
		return x.Config
	}
	return nil
}

type ConnectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectResponse) Reset() {
	*x = ConnectResponse{}
	mi := &file_plugins_proto_storage_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectResponse) ProtoMessage() {}

func (x *ConnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_proto_storage_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectResponse.ProtoReflect.Descriptor instead.
func (*ConnectResponse) Descriptor() ([]byte, []int) {
	return file_plugins_proto_storage_proto_rawDescGZIP(), []int{10}
}

func (x *ConnectResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DisconnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectRequest) Reset() {
	*x = DisconnectRequest{}
	mi := &file_plugins_proto_storage_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectRequest) ProtoMessage() {}

func (x *DisconnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_proto_storage_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectRequest.ProtoReflect.Descriptor instead.
func (*DisconnectRequest) Descriptor() ([]byte, []int) {
	return file_plugins_proto_storage_proto_rawDescGZIP(), []int{11}
}

type DisconnectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectResponse) Reset() {
	*x = DisconnectResponse{}
	mi := &file_plugins_proto_storage_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectResponse) ProtoMessage() {}

func (x *DisconnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_proto_storage_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectResponse.ProtoReflect.Descriptor instead.
func (*DisconnectResponse) Descriptor() ([]byte, []int) {
	return file_plugins_proto_storage_proto_rawDescGZIP(), []int{12}
}

func (x *DisconnectResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type IsConnectedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsConnectedRequest) Reset() {
	*x = IsConnectedRequest{}
	mi := &file_plugins_proto_storage_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsConnectedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsConnectedRequest) ProtoMessage() {}

func (x *IsConnectedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_proto_storage_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsConnectedRequest.ProtoReflect.Descriptor instead.
func (*IsConnectedRequest) Descriptor() ([]byte, []int) {
	return file_plugins_proto_storage_proto_rawDescGZIP(), []int{13}
}

type IsConnectedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Connected     bool                   `protobuf:"varint,1,opt,name=connected,proto3" json:"connected,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsConnectedResponse) Reset() {
	*x = IsConnectedResponse{}
	mi := &file_plugins_proto_storage_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsConnectedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsConnectedResponse) ProtoMessage() {}

func (x *IsConnectedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_proto_storage_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsConnectedResponse.ProtoReflect.Descriptor instead.
func (*IsConnectedResponse) Descriptor() ([]byte, []int) {
	return file_plugins_proto_storage_proto_rawDescGZIP(), []int{14}
}

func (x *IsConnectedResponse) GetConnected() bool {
	if x != nil {
		return x.Connected
	}
	return false
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_plugins_proto_storage_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_proto_storage_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_plugins_proto_storage_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_plugins_proto_storage_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_proto_storage_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_plugins_proto_storage_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type MoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OldPath       string                 `protobuf:"bytes,1,opt,name=old_path,json=oldPath,proto3" json:"old_path,omitempty"`
	NewPath       string                 `protobuf:"bytes,2,opt,name=new_path,json=newPath,proto3" json:"new_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveRequest) Reset() {
	*x = MoveRequest{}
	mi := &file_plugins_proto_storage_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveRequest) ProtoMessage() {}

func (x *MoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_proto_storage_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveRequest.ProtoReflect.Descriptor instead.
func (*MoveRequest) Descriptor() ([]byte, []int) {
	return file_plugins_proto_storage_proto_rawDescGZIP(), []int{17}
}

func (x *MoveRequest) GetOldPath() string {
	if x != nil {
		return x.OldPath
	}
	return ""
}

func (x *MoveRequest) GetNewPath() string {
	if x != nil {
		return x.NewPath
	}
	return ""
}

type MoveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveResponse) Reset() {
	*x = MoveResponse{}
	mi := &file_plugins_proto_storage_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveResponse) ProtoMessage() {}

func (x *MoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_proto_storage_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveResponse.ProtoReflect.Descriptor instead.
func (*MoveResponse) Descriptor() ([]byte, []int) {
	return file_plugins_proto_storage_proto_rawDescGZIP(), []int{18}
}

func (x *MoveResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_plugins_proto_storage_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_proto_storage_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_plugins_proto_storage_proto_rawDescGZIP(), []int{19}
}

func (x *ListRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*FileInfoProto       `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_plugins_proto_storage_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_proto_storage_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_plugins_proto_storage_proto_rawDescGZIP(), []int{20}
}

func (x *ListResponse) GetFiles() []*FileInfoProto {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *ListResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type StatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatRequest) Reset() {
	*x = StatRequest{}
	mi := &file_plugins_proto_storage_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatRequest) ProtoMessage() {}

func (x *StatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_proto_storage_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatRequest.ProtoReflect.Descriptor instead.
func (*StatRequest) Descriptor() ([]byte, []int) {
	return file_plugins_proto_storage_proto_rawDescGZIP(), []int{21}
}

func (x *StatRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type StatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          *FileInfoProto         `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatResponse) Reset() {
	*x = StatResponse{}
	mi := &file_plugins_proto_storage_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatResponse) ProtoMessage() {}

func (x *StatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_proto_storage_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatResponse.ProtoReflect.Descriptor instead.
func (*StatResponse) Descriptor() ([]byte, []int) {
	return file_plugins_proto_storage_proto_rawDescGZIP(), []int{22}
}

func (x *StatResponse) GetFile() *FileInfoProto {
	if x != nil {
		return x.File
	}
	return nil
}

func (x *StatResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CreateDirRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDirRequest) Reset() {
	*x = CreateDirRequest{}
	mi := &file_plugins_proto_storage_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDirRequest) ProtoMessage() {}

func (x *CreateDirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_proto_storage_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDirRequest.ProtoReflect.Descriptor instead.
func (*CreateDirRequest) Descriptor() ([]byte, []int) {
	return file_plugins_proto_storage_proto_rawDescGZIP(), []int{23}
}

func (x *CreateDirRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type CreateDirResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDirResponse) Reset() {
	*x = CreateDirResponse{}
	mi := &file_plugins_proto_storage_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDirResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDirResponse) ProtoMessage() {}

func (x *CreateDirResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_proto_storage_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDirResponse.ProtoReflect.Descriptor instead.
func (*CreateDirResponse) Descriptor() ([]byte, []int) {
	return file_plugins_proto_storage_proto_rawDescGZIP(), []int{24}
}

func (x *CreateDirResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type WatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	mi := &file_plugins_proto_storage_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_proto_storage_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_plugins_proto_storage_proto_rawDescGZIP(), []int{25}
}

func (x *WatchRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// WatchEvent is streamed by the server until the client cancels the context.
type WatchEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *FileEventProto        `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"` // non-empty on terminal error
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchEvent) Reset() {
	*x = WatchEvent{}
	mi := &file_plugins_proto_storage_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchEvent) ProtoMessage() {}

func (x *WatchEvent) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_proto_storage_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchEvent.ProtoReflect.Descriptor instead.
func (*WatchEvent) Descriptor() ([]byte, []int) {
	return file_plugins_proto_storage_proto_rawDescGZIP(), []int{26}
}

func (x *WatchEvent) GetEvent() *FileEventProto {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *WatchEvent) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type QuotaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuotaRequest) Reset() {
	*x = QuotaRequest{}
	mi := &file_plugins_proto_storage_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuotaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuotaRequest) ProtoMessage() {}

func (x *QuotaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_proto_storage_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuotaRequest.ProtoReflect.Descriptor instead.
func (*QuotaRequest) Descriptor() ([]byte, []int) {
	return file_plugins_proto_storage_proto_rawDescGZIP(), []int{27}
}

type QuotaResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Free  int64                  `protobuf:"varint,1,opt,name=free,proto3" json:"free,omitempty"`
	Total int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	// Deprecated: since v0.7.0 the server returns gRPC status errors instead of
	// populating this field. Kept for wire-format compatibility with pre-v0.7.0
	// plugin binaries. The client (plugins/grpc/client.go GetQuota) still reads
	// it as a fallback. Do NOT remove field number 3.
	Error         string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuotaResponse) Reset() {
	*x = QuotaResponse{}
	mi := &file_plugins_proto_storage_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuotaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuotaResponse) ProtoMessage() {}

func (x *QuotaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_proto_storage_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuotaResponse.ProtoReflect.Descriptor instead.
func (*QuotaResponse) Descriptor() ([]byte, []int) {
	return file_plugins_proto_storage_proto_rawDescGZIP(), []int{28}
}

func (x *QuotaResponse) GetFree() int64 {
	if x != nil {
		return x.Free
	}
	return 0
}

func (x *QuotaResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *QuotaResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// ReadAtRequest initiates a ReadAt RPC.
type ReadAtRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RemotePath    string                 `protobuf:"bytes,1,opt,name=remote_path,json=remotePath,proto3" json:"remote_path,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Length        int64                  `protobuf:"varint,3,opt,name=length,proto3" json:"length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadAtRequest) Reset() {
	*x = ReadAtRequest{}
	mi := &file_plugins_proto_storage_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadAtRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadAtRequest) ProtoMessage() {}

func (x *ReadAtRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_proto_storage_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadAtRequest.ProtoReflect.Descriptor instead.
func (*ReadAtRequest) Descriptor() ([]byte, []int) {
	return file_plugins_proto_storage_proto_rawDescGZIP(), []int{29}
}

func (x *ReadAtRequest) GetRemotePath() string {
	if x != nil {
		return x.RemotePath
	}
	return ""
}

func (x *ReadAtRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ReadAtRequest) GetLength() int64 {
	if x != nil {
		return x.Length
	}
	return 0
}

// ReadAtResponse carries the bytes read and an optional error string.
type ReadAtResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`   // bytes read; len(data) may be less than length on EOF
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"` // non-empty on terminal error
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadAtResponse) Reset() {
	*x = ReadAtResponse{}
	mi := &file_plugins_proto_storage_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadAtResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadAtResponse) ProtoMessage() {}

func (x *ReadAtResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_proto_storage_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadAtResponse.ProtoReflect.Descriptor instead.
func (*ReadAtResponse) Descriptor() ([]byte, []int) {
	return file_plugins_proto_storage_proto_rawDescGZIP(), []int{30}
}

func (x *ReadAtResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ReadAtResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// ChunkSizeRequest has no fields; it is a capability query.
type ChunkSizeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkSizeRequest) Reset() {
	*x = ChunkSizeRequest{}
	mi := &file_plugins_proto_storage_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkSizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkSizeRequest) ProtoMessage() {}

func (x *ChunkSizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_proto_storage_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkSizeRequest.ProtoReflect.Descriptor instead.
func (*ChunkSizeRequest) Descriptor() ([]byte, []int) {
	return file_plugins_proto_storage_proto_rawDescGZIP(), []int{31}
}

// ChunkSizeResponse returns the natural I/O granularity of the backend in bytes.
// Returns 0 when the backend has no native chunk size (use global default).
type ChunkSizeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkSize     int64                  `protobuf:"varint,1,opt,name=chunk_size,json=chunkSize,proto3" json:"chunk_size,omitempty"` // 0 = use global default
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkSizeResponse) Reset() {
	*x = ChunkSizeResponse{}
	mi := &file_plugins_proto_storage_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkSizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkSizeResponse) ProtoMessage() {}

func (x *ChunkSizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_proto_storage_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkSizeResponse.ProtoReflect.Descriptor instead.
func (*ChunkSizeResponse) Descriptor() ([]byte, []int) {
	return file_plugins_proto_storage_proto_rawDescGZIP(), []int{32}
}

func (x *ChunkSizeResponse) GetChunkSize() int64 {
	if x != nil {
		return x.ChunkSize
	}
	return 0
}

type ParamSpecProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,20,opt,name=key,proto3" json:"key,omitempty"`
	Label         string                 `protobuf:"bytes,21,opt,name=label,proto3" json:"label,omitempty"`
	Type          string                 `protobuf:"bytes,22,opt,name=type,proto3" json:"type,omitempty"` // "string" | "password" | "path" | "select" | "bool" | "number"
	Required      bool                   `protobuf:"varint,23,opt,name=required,proto3" json:"required,omitempty"`
	DefaultVal    string                 `protobuf:"bytes,24,opt,name=default_val,json=defaultVal,proto3" json:"default_val,omitempty"`
	Placeholder   string                 `protobuf:"bytes,25,opt,name=placeholder,proto3" json:"placeholder,omitempty"`
	Options       []string               `protobuf:"bytes,26,rep,name=options,proto3" json:"options,omitempty"`
	HelpText      string                 `protobuf:"bytes,27,opt,name=help_text,json=helpText,proto3" json:"help_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParamSpecProto) Reset() {
	*x = ParamSpecProto{}
	mi := &file_plugins_proto_storage_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParamSpecProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParamSpecProto) ProtoMessage() {}

func (x *ParamSpecProto) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_proto_storage_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParamSpecProto.ProtoReflect.Descriptor instead.
func (*ParamSpecProto) Descriptor() ([]byte, []int) {
	return file_plugins_proto_storage_proto_rawDescGZIP(), []int{33}
}

func (x *ParamSpecProto) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ParamSpecProto) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *ParamSpecProto) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ParamSpecProto) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *ParamSpecProto) GetDefaultVal() string {
	if x != nil {
		return x.DefaultVal
	}
	return ""
}

func (x *ParamSpecProto) GetPlaceholder() string {
	if x != nil {
		return x.Placeholder
	}
	return ""
}

func (x *ParamSpecProto) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *ParamSpecProto) GetHelpText() string {
	if x != nil {
		return x.HelpText
	}
	return ""
}

type DescribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeRequest) Reset() {
	*x = DescribeRequest{}
	mi := &file_plugins_proto_storage_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeRequest) ProtoMessage() {}

func (x *DescribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_proto_storage_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeRequest.ProtoReflect.Descriptor instead.
func (*DescribeRequest) Descriptor() ([]byte, []int) {
	return file_plugins_proto_storage_proto_rawDescGZIP(), []int{34}
}

type DescribeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,20,opt,name=type,proto3" json:"type,omitempty"`
	DisplayName   string                 `protobuf:"bytes,21,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Description   string                 `protobuf:"bytes,22,opt,name=description,proto3" json:"description,omitempty"`
	Params        []*ParamSpecProto      `protobuf:"bytes,23,rep,name=params,proto3" json:"params,omitempty"`
	Version       string                 `protobuf:"bytes,24,opt,name=version,proto3" json:"version,omitempty"` // semver injected at build time via ldflags, e.g. "1.5.2"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeResponse) Reset() {
	*x = DescribeResponse{}
	mi := &file_plugins_proto_storage_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeResponse) ProtoMessage() {}

func (x *DescribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_proto_storage_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeResponse.ProtoReflect.Descriptor instead.
func (*DescribeResponse) Descriptor() ([]byte, []int) {
	return file_plugins_proto_storage_proto_rawDescGZIP(), []int{35}
}

func (x *DescribeResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DescribeResponse) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *DescribeResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *DescribeResponse) GetParams() []*ParamSpecProto {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *DescribeResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_plugins_proto_storage_proto protoreflect.FileDescriptor

const file_plugins_proto_storage_proto_rawDesc = "" +
	"\n" +
	"\x1bplugins/proto/storage.proto\x12\x15ghostdrive.storage.v1\"\xee\x02\n" +
	"\x12BackendConfigProto\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x18\n" +
	"\aenabled\x18\x04 \x01(\bR\aenabled\x12\x1b\n" +
	"\tauto_sync\x18\x05 \x01(\bR\bautoSync\x12M\n" +
	"\x06params\x18\x06 \x03(\v25.ghostdrive.storage.v1.BackendConfigProto.ParamsEntryR\x06params\x12\x19\n" +
	"\bsync_dir\x18\a \x01(\tR\asyncDir\x12\x1f\n" +
	"\vremote_path\x18\b \x01(\tR\n" +
	"remotePath\x12\x1d\n" +
	"\n" +
	"local_path\x18\t \x01(\tR\tlocalPath\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01J\x04\b\n" +
	"\x10\x14\"\xfe\x01\n" +
	"\rFileInfoProto\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12\x15\n" +
	"\x06is_dir\x18\x04 \x01(\bR\x05isDir\x12\"\n" +
	"\rmod_time_unix\x18\x05 \x01(\x03R\vmodTimeUnix\x12\x12\n" +
	"\x04etag\x18\x06 \x01(\tR\x04etag\x12%\n" +
	"\x0eis_placeholder\x18\a \x01(\bR\risPlaceholder\x12\x1b\n" +
	"\tis_cached\x18\b \x01(\bR\bisCached\x12\x18\n" +
	"\aversion\x18\x14 \x01(\tR\aversionJ\x04\b\t\x10\x14\"\x9b\x02\n" +
	"\x0eFileEventProto\x12\x1d\n" +
	"\n" +
	"event_type\x18\x01 \x01(\tR\teventType\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x19\n" +
	"\bold_path\x18\x03 \x01(\tR\aoldPath\x12%\n" +
	"\x0etimestamp_unix\x18\x04 \x01(\x03R\rtimestampUnix\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\x12\"\n" +
	"\rmod_time_unix\x18\x06 \x01(\x03R\vmodTimeUnix\x123\n" +
	"\x16previous_mod_time_unix\x18\a \x01(\x03R\x13previousModTimeUnix\x12#\n" +
	"\rmetadata_only\x18\b \x01(\bR\fmetadataOnly\"\x82\x01\n" +
	"\vUploadChunk\x12\x1d\n" +
	"\n" +
	"local_path\x18\x01 \x01(\tR\tlocalPath\x12\x1f\n" +
	"\vremote_path\x18\x02 \x01(\tR\n" +
	"remotePath\x12\x1f\n" +
	"\vtotal_bytes\x18\x03 \x01(\x03R\n" +
	"totalBytes\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\"$\n" +
	"\fUploadResult\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"Q\n" +
	"\x0fDownloadRequest\x12\x1f\n" +
	"\vremote_path\x18\x01 \x01(\tR\n" +
	"remotePath\x12\x1d\n" +
	"\n" +
	"local_path\x18\x02 \x01(\tR\tlocalPath\"y\n" +
	"\rDownloadChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1d\n" +
	"\n" +
	"bytes_done\x18\x02 \x01(\x03R\tbytesDone\x12\x1f\n" +
	"\vbytes_total\x18\x03 \x01(\x03R\n" +
	"bytesTotal\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\r\n" +
	"\vNameRequest\"\"\n" +
	"\fNameResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"S\n" +
	"\x0eConnectRequest\x12A\n" +
	"\x06config\x18\x01 \x01(\v2).ghostdrive.storage.v1.BackendConfigProtoR\x06config\"'\n" +
	"\x0fConnectResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"\x13\n" +
	"\x11DisconnectRequest\"*\n" +
	"\x12DisconnectResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"\x14\n" +
	"\x12IsConnectedRequest\"3\n" +
	"\x13IsConnectedResponse\x12\x1c\n" +
	"\tconnected\x18\x01 \x01(\bR\tconnected\"#\n" +
	"\rDeleteRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"&\n" +
	"\x0eDeleteResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"C\n" +
	"\vMoveRequest\x12\x19\n" +
	"\bold_path\x18\x01 \x01(\tR\aoldPath\x12\x19\n" +
	"\bnew_path\x18\x02 \x01(\tR\anewPath\"$\n" +
	"\fMoveResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"!\n" +
	"\vListRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"`\n" +
	"\fListResponse\x12:\n" +
	"\x05files\x18\x01 \x03(\v2$.ghostdrive.storage.v1.FileInfoProtoR\x05files\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"!\n" +
	"\vStatRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"^\n" +
	"\fStatResponse\x128\n" +
	"\x04file\x18\x01 \x01(\v2$.ghostdrive.storage.v1.FileInfoProtoR\x04file\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"&\n" +
	"\x10CreateDirRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\")\n" +
	"\x11CreateDirResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"\"\n" +
	"\fWatchRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"_\n" +
	"\n" +
	"WatchEvent\x12;\n" +
	"\x05event\x18\x01 \x01(\v2%.ghostdrive.storage.v1.FileEventProtoR\x05event\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x0e\n" +
	"\fQuotaRequest\"O\n" +
	"\rQuotaResponse\x12\x12\n" +
	"\x04free\x18\x01 \x01(\x03R\x04free\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"`\n" +
	"\rReadAtRequest\x12\x1f\n" +
	"\vremote_path\x18\x01 \x01(\tR\n" +
	"remotePath\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12\x16\n" +
	"\x06length\x18\x03 \x01(\x03R\x06length\":\n" +
	"\x0eReadAtResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x12\n" +
	"\x10ChunkSizeRequest\"2\n" +
	"\x11ChunkSizeResponse\x12\x1d\n" +
	"\n" +
	"chunk_size\x18\x01 \x01(\x03R\tchunkSize\"\xe2\x01\n" +
	"\x0eParamSpecProto\x12\x10\n" +
	"\x03key\x18\x14 \x01(\tR\x03key\x12\x14\n" +
	"\x05label\x18\x15 \x01(\tR\x05label\x12\x12\n" +
	"\x04type\x18\x16 \x01(\tR\x04type\x12\x1a\n" +
	"\brequired\x18\x17 \x01(\bR\brequired\x12\x1f\n" +
	"\vdefault_val\x18\x18 \x01(\tR\n" +
	"defaultVal\x12 \n" +
	"\vplaceholder\x18\x19 \x01(\tR\vplaceholder\x12\x18\n" +
	"\aoptions\x18\x1a \x03(\tR\aoptions\x12\x1b\n" +
	"\thelp_text\x18\x1b \x01(\tR\bhelpText\"\x11\n" +
	"\x0fDescribeRequest\"\xc4\x01\n" +
	"\x10DescribeResponse\x12\x12\n" +
	"\x04type\x18\x14 \x01(\tR\x04type\x12!\n" +
	"\fdisplay_name\x18\x15 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\x16 \x01(\tR\vdescription\x12=\n" +
	"\x06params\x18\x17 \x03(\v2%.ghostdrive.storage.v1.ParamSpecProtoR\x06params\x12\x18\n" +
	"\aversion\x18\x18 \x01(\tR\aversion2\x9d\v\n" +
	"\x0eStorageService\x12O\n" +
	"\x04Name\x12\".ghostdrive.storage.v1.NameRequest\x1a#.ghostdrive.storage.v1.NameResponse\x12X\n" +
	"\aConnect\x12%.ghostdrive.storage.v1.ConnectRequest\x1a&.ghostdrive.storage.v1.ConnectResponse\x12a\n" +
	"\n" +
	"Disconnect\x12(.ghostdrive.storage.v1.DisconnectRequest\x1a).ghostdrive.storage.v1.DisconnectResponse\x12d\n" +
	"\vIsConnected\x12).ghostdrive.storage.v1.IsConnectedRequest\x1a*.ghostdrive.storage.v1.IsConnectedResponse\x12S\n" +
	"\x06Upload\x12\".ghostdrive.storage.v1.UploadChunk\x1a#.ghostdrive.storage.v1.UploadResult(\x01\x12Z\n" +
	"\bDownload\x12&.ghostdrive.storage.v1.DownloadRequest\x1a$.ghostdrive.storage.v1.DownloadChunk0\x01\x12U\n" +
	"\x06Delete\x12$.ghostdrive.storage.v1.DeleteRequest\x1a%.ghostdrive.storage.v1.DeleteResponse\x12O\n" +
	"\x04Move\x12\".ghostdrive.storage.v1.MoveRequest\x1a#.ghostdrive.storage.v1.MoveResponse\x12O\n" +
	"\x04List\x12\".ghostdrive.storage.v1.ListRequest\x1a#.ghostdrive.storage.v1.ListResponse\x12O\n" +
	"\x04Stat\x12\".ghostdrive.storage.v1.StatRequest\x1a#.ghostdrive.storage.v1.StatResponse\x12^\n" +
	"\tCreateDir\x12'.ghostdrive.storage.v1.CreateDirRequest\x1a(.ghostdrive.storage.v1.CreateDirResponse\x12Q\n" +
	"\x05Watch\x12#.ghostdrive.storage.v1.WatchRequest\x1a!.ghostdrive.storage.v1.WatchEvent0\x01\x12U\n" +
	"\bGetQuota\x12#.ghostdrive.storage.v1.QuotaRequest\x1a$.ghostdrive.storage.v1.QuotaResponse\x12[\n" +
	"\bDescribe\x12&.ghostdrive.storage.v1.DescribeRequest\x1a'.ghostdrive.storage.v1.DescribeResponse\x12U\n" +
	"\x06ReadAt\x12$.ghostdrive.storage.v1.ReadAtRequest\x1a%.ghostdrive.storage.v1.ReadAtResponse\x12^\n" +
	"\tChunkSize\x12'.ghostdrive.storage.v1.ChunkSizeRequest\x1a(.ghostdrive.storage.v1.ChunkSizeResponseB7Z5github.com/CCoupel/GhostDrive/plugins/proto;storagepbb\x06proto3"

var (
	file_plugins_proto_storage_proto_rawDescOnce sync.Once
	file_plugins_proto_storage_proto_rawDescData []byte
)

func file_plugins_proto_storage_proto_rawDescGZIP() []byte {
	file_plugins_proto_storage_proto_rawDescOnce.Do(func() {
		file_plugins_proto_storage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugins_proto_storage_proto_rawDesc), len(file_plugins_proto_storage_proto_rawDesc)))
	})
	return file_plugins_proto_storage_proto_rawDescData
}

var file_plugins_proto_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 37)
var file_plugins_proto_storage_proto_goTypes = []any{
	(*BackendConfigProto)(nil),  // 0: ghostdrive.storage.v1.BackendConfigProto
	(*FileInfoProto)(nil),       // 1: ghostdrive.storage.v1.FileInfoProto
	(*FileEventProto)(nil),      // 2: ghostdrive.storage.v1.FileEventProto
	(*UploadChunk)(nil),         // 3: ghostdrive.storage.v1.UploadChunk
	(*UploadResult)(nil),        // 4: ghostdrive.storage.v1.UploadResult
	(*DownloadRequest)(nil),     // 5: ghostdrive.storage.v1.DownloadRequest
	(*DownloadChunk)(nil),       // 6: ghostdrive.storage.v1.DownloadChunk
	(*NameRequest)(nil),         // 7: ghostdrive.storage.v1.NameRequest
	(*NameResponse)(nil),        // 8: ghostdrive.storage.v1.NameResponse
	(*ConnectRequest)(nil),      // 9: ghostdrive.storage.v1.ConnectRequest
	(*ConnectResponse)(nil),     // 10: ghostdrive.storage.v1.ConnectResponse
	(*DisconnectRequest)(nil),   // 11: ghostdrive.storage.v1.DisconnectRequest
	(*DisconnectResponse)(nil),  // 12: ghostdrive.storage.v1.DisconnectResponse
	(*IsConnectedRequest)(nil),  // 13: ghostdrive.storage.v1.IsConnectedRequest
	(*IsConnectedResponse)(nil), // 14: ghostdrive.storage.v1.IsConnectedResponse
	(*DeleteRequest)(nil),       // 15: ghostdrive.storage.v1.DeleteRequest
	(*DeleteResponse)(nil),      // 16: ghostdrive.storage.v1.DeleteResponse
	(*MoveRequest)(nil),         // 17: ghostdrive.storage.v1.MoveRequest
	(*MoveResponse)(nil),        // 18: ghostdrive.storage.v1.MoveResponse
	(*ListRequest)(nil),         // 19: ghostdrive.storage.v1.ListRequest
	(*ListResponse)(nil),        // 20: ghostdrive.storage.v1.ListResponse
	(*StatRequest)(nil),         // 21: ghostdrive.storage.v1.StatRequest
	(*StatResponse)(nil),        // 22: ghostdrive.storage.v1.StatResponse
	(*CreateDirRequest)(nil),    // 23: ghostdrive.storage.v1.CreateDirRequest
	(*CreateDirResponse)(nil),   // 24: ghostdrive.storage.v1.CreateDirResponse
	(*WatchRequest)(nil),        // 25: ghostdrive.storage.v1.WatchRequest
	(*WatchEvent)(nil),          // 26: ghostdrive.storage.v1.WatchEvent
	(*QuotaRequest)(nil),        // 27: ghostdrive.storage.v1.QuotaRequest
	(*QuotaResponse)(nil),       // 28: ghostdrive.storage.v1.QuotaResponse
	(*ReadAtRequest)(nil),       // 29: ghostdrive.storage.v1.ReadAtRequest
	(*ReadAtResponse)(nil),      // 30: ghostdrive.storage.v1.ReadAtResponse
	(*ChunkSizeRequest)(nil),    // 31: ghostdrive.storage.v1.ChunkSizeRequest
	(*ChunkSizeResponse)(nil),   // 32: ghostdrive.storage.v1.ChunkSizeResponse
	(*ParamSpecProto)(nil),      // 33: ghostdrive.storage.v1.ParamSpecProto
	(*DescribeRequest)(nil),     // 34: ghostdrive.storage.v1.DescribeRequest
	(*DescribeResponse)(nil),    // 35: ghostdrive.storage.v1.DescribeResponse
	nil,                         // 36: ghostdrive.storage.v1.BackendConfigProto.ParamsEntry
}
var file_plugins_proto_storage_proto_depIdxs = []int32{
	36, // 0: ghostdrive.storage.v1.BackendConfigProto.params:type_name -> ghostdrive.storage.v1.BackendConfigProto.ParamsEntry
	0,  // 1: ghostdrive.storage.v1.ConnectRequest.config:type_name -> ghostdrive.storage.v1.BackendConfigProto
	1,  // 2: ghostdrive.storage.v1.ListResponse.files:type_name -> ghostdrive.storage.v1.FileInfoProto
	1,  // 3: ghostdrive.storage.v1.StatResponse.file:type_name -> ghostdrive.storage.v1.FileInfoProto
	2,  // 4: ghostdrive.storage.v1.WatchEvent.event:type_name -> ghostdrive.storage.v1.FileEventProto
	33, // 5: ghostdrive.storage.v1.DescribeResponse.params:type_name -> ghostdrive.storage.v1.ParamSpecProto
	7,  // 6: ghostdrive.storage.v1.StorageService.Name:input_type -> ghostdrive.storage.v1.NameRequest
	9,  // 7: ghostdrive.storage.v1.StorageService.Connect:input_type -> ghostdrive.storage.v1.ConnectRequest
	11, // 8: ghostdrive.storage.v1.StorageService.Disconnect:input_type -> ghostdrive.storage.v1.DisconnectRequest
	13, // 9: ghostdrive.storage.v1.StorageService.IsConnected:input_type -> ghostdrive.storage.v1.IsConnectedRequest
	3,  // 10: ghostdrive.storage.v1.StorageService.Upload:input_type -> ghostdrive.storage.v1.UploadChunk
	5,  // 11: ghostdrive.storage.v1.StorageService.Download:input_type -> ghostdrive.storage.v1.DownloadRequest
	15, // 12: ghostdrive.storage.v1.StorageService.Delete:input_type -> ghostdrive.storage.v1.DeleteRequest
	17, // 13: ghostdrive.storage.v1.StorageService.Move:input_type -> ghostdrive.storage.v1.MoveRequest
	19, // 14: ghostdrive.storage.v1.StorageService.List:input_type -> ghostdrive.storage.v1.ListRequest
	21, // 15: ghostdrive.storage.v1.StorageService.Stat:input_type -> ghostdrive.storage.v1.StatRequest
	23, // 16: ghostdrive.storage.v1.StorageService.CreateDir:input_type -> ghostdrive.storage.v1.CreateDirRequest
	25, // 17: ghostdrive.storage.v1.StorageService.Watch:input_type -> ghostdrive.storage.v1.WatchRequest
	27, // 18: ghostdrive.storage.v1.StorageService.GetQuota:input_type -> ghostdrive.storage.v1.QuotaRequest
	34, // 19: ghostdrive.storage.v1.StorageService.Describe:input_type -> ghostdrive.storage.v1.DescribeRequest
	29, // 20: ghostdrive.storage.v1.StorageService.ReadAt:input_type -> ghostdrive.storage.v1.ReadAtRequest
	31, // 21: ghostdrive.storage.v1.StorageService.ChunkSize:input_type -> ghostdrive.storage.v1.ChunkSizeRequest
	8,  // 22: ghostdrive.storage.v1.StorageService.Name:output_type -> ghostdrive.storage.v1.NameResponse
	10, // 23: ghostdrive.storage.v1.StorageService.Connect:output_type -> ghostdrive.storage.v1.ConnectResponse
	12, // 24: ghostdrive.storage.v1.StorageService.Disconnect:output_type -> ghostdrive.storage.v1.DisconnectResponse
	14, // 25: ghostdrive.storage.v1.StorageService.IsConnected:output_type -> ghostdrive.storage.v1.IsConnectedResponse
	4,  // 26: ghostdrive.storage.v1.StorageService.Upload:output_type -> ghostdrive.storage.v1.UploadResult
	6,  // 27: ghostdrive.storage.v1.StorageService.Download:output_type -> ghostdrive.storage.v1.DownloadChunk
	16, // 28: ghostdrive.storage.v1.StorageService.Delete:output_type -> ghostdrive.storage.v1.DeleteResponse
	18, // 29: ghostdrive.storage.v1.StorageService.Move:output_type -> ghostdrive.storage.v1.MoveResponse
	20, // 30: ghostdrive.storage.v1.StorageService.List:output_type -> ghostdrive.storage.v1.ListResponse
	22, // 31: ghostdrive.storage.v1.StorageService.Stat:output_type -> ghostdrive.storage.v1.StatResponse
	24, // 32: ghostdrive.storage.v1.StorageService.CreateDir:output_type -> ghostdrive.storage.v1.CreateDirResponse
	26, // 33: ghostdrive.storage.v1.StorageService.Watch:output_type -> ghostdrive.storage.v1.WatchEvent
	28, // 34: ghostdrive.storage.v1.StorageService.GetQuota:output_type -> ghostdrive.storage.v1.QuotaResponse
	35, // 35: ghostdrive.storage.v1.StorageService.Describe:output_type -> ghostdrive.storage.v1.DescribeResponse
	30, // 36: ghostdrive.storage.v1.StorageService.ReadAt:output_type -> ghostdrive.storage.v1.ReadAtResponse
	32, // 37: ghostdrive.storage.v1.StorageService.ChunkSize:output_type -> ghostdrive.storage.v1.ChunkSizeResponse
	22, // [22:38] is the sub-list for method output_type
	6,  // [6:22] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_plugins_proto_storage_proto_init() }
func file_plugins_proto_storage_proto_init() {
	if File_plugins_proto_storage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugins_proto_storage_proto_rawDesc), len(file_plugins_proto_storage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   37,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plugins_proto_storage_proto_goTypes,
		DependencyIndexes: file_plugins_proto_storage_proto_depIdxs,
		MessageInfos:      file_plugins_proto_storage_proto_msgTypes,
	}.Build()
	File_plugins_proto_storage_proto = out.File
	file_plugins_proto_storage_proto_goTypes = nil
	file_plugins_proto_storage_proto_depIdxs = nil
}
