// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddBackend(arg1) {
  return window['go']['app']['App']['AddBackend'](arg1);
}

export function Context() {
  return window['go']['app']['App']['Context']();
}

export function Emit(arg1, arg2) {
  return window['go']['app']['App']['Emit'](arg1, arg2);
}

export function ForceSync(arg1) {
  return window['go']['app']['App']['ForceSync'](arg1);
}

export function GetBackendStatuses() {
  return window['go']['app']['App']['GetBackendStatuses']();
}

export function GetConfig() {
  return window['go']['app']['App']['GetConfig']();
}

export function GetSyncState() {
  return window['go']['app']['App']['GetSyncState']();
}

export function GetVersion() {
  return window['go']['app']['App']['GetVersion']();
}

export function OpenSyncFolder(arg1) {
  return window['go']['app']['App']['OpenSyncFolder'](arg1);
}

export function PauseSync(arg1) {
  return window['go']['app']['App']['PauseSync'](arg1);
}

export function Quit() {
  return window['go']['app']['App']['Quit']();
}

export function RemoveBackend(arg1) {
  return window['go']['app']['App']['RemoveBackend'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['app']['App']['SaveConfig'](arg1);
}

export function StartSync(arg1) {
  return window['go']['app']['App']['StartSync'](arg1);
}

export function StopSync(arg1) {
  return window['go']['app']['App']['StopSync'](arg1);
}

export function TestBackendConnection(arg1) {
  return window['go']['app']['App']['TestBackendConnection'](arg1);
}
