// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddBackend(arg1) {
  return window['go']['app']['App']['AddBackend'](arg1);
}

export function ClearCache() {
  return window['go']['app']['App']['ClearCache']();
}

export function Context() {
  return window['go']['app']['App']['Context']();
}

export function DownloadFile(arg1, arg2) {
  return window['go']['app']['App']['DownloadFile'](arg1, arg2);
}

export function Emit(arg1, arg2) {
  return window['go']['app']['App']['Emit'](arg1, arg2);
}

export function ForceSync(arg1) {
  return window['go']['app']['App']['ForceSync'](arg1);
}

export function GetAvailableBackendTypes() {
  return window['go']['app']['App']['GetAvailableBackendTypes']();
}

export function GetAvailableDriveLetters() {
  return window['go']['app']['App']['GetAvailableDriveLetters']();
}

export function GetBackendStatuses() {
  return window['go']['app']['App']['GetBackendStatuses']();
}

export function GetCacheStats() {
  return window['go']['app']['App']['GetCacheStats']();
}

export function GetConfig() {
  return window['go']['app']['App']['GetConfig']();
}

export function GetDriveStatus() {
  return window['go']['app']['App']['GetDriveStatus']();
}

export function GetGhostDriveRoot() {
  return window['go']['app']['App']['GetGhostDriveRoot']();
}

export function GetLoadedPlugins() {
  return window['go']['app']['App']['GetLoadedPlugins']();
}

export function GetMountPoint() {
  return window['go']['app']['App']['GetMountPoint']();
}

export function GetSyncState() {
  return window['go']['app']['App']['GetSyncState']();
}

export function GetVersion() {
  return window['go']['app']['App']['GetVersion']();
}

export function ListFiles(arg1, arg2) {
  return window['go']['app']['App']['ListFiles'](arg1, arg2);
}

export function MountDrive() {
  return window['go']['app']['App']['MountDrive']();
}

export function OpenSyncFolder(arg1) {
  return window['go']['app']['App']['OpenSyncFolder'](arg1);
}

export function PauseSync(arg1) {
  return window['go']['app']['App']['PauseSync'](arg1);
}

export function Quit() {
  return window['go']['app']['App']['Quit']();
}

export function ReloadPlugins() {
  return window['go']['app']['App']['ReloadPlugins']();
}

export function RemoveBackend(arg1) {
  return window['go']['app']['App']['RemoveBackend'](arg1);
}

export function ResumeSync(arg1) {
  return window['go']['app']['App']['ResumeSync'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['app']['App']['SaveConfig'](arg1);
}

export function SelectDirectory() {
  return window['go']['app']['App']['SelectDirectory']();
}

export function SetAutoSync(arg1, arg2) {
  return window['go']['app']['App']['SetAutoSync'](arg1, arg2);
}

export function SetBackendEnabled(arg1, arg2) {
  return window['go']['app']['App']['SetBackendEnabled'](arg1, arg2);
}

export function StartSync(arg1) {
  return window['go']['app']['App']['StartSync'](arg1);
}

export function StopSync(arg1) {
  return window['go']['app']['App']['StopSync'](arg1);
}

export function TestBackendConnection(arg1) {
  return window['go']['app']['App']['TestBackendConnection'](arg1);
}

export function UnmountDrive() {
  return window['go']['app']['App']['UnmountDrive']();
}
