package sync

// Tests for the Engine file-state cache introduced in v2.2 (#136).
//
// Coverage:
//   - GetFileState / SetFileState thread-safety (concurrent goroutines)
//   - State transitions U→S→E via makeStateUpdater
//   - sync:file-state-changed event emitted on each transition
//   - L-guard: FileEventDeleted on a FileStateLocal file skips remote ActionDelete
//   - Intent consumed when a file transitions U→S (#143)

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"sync"
	"testing"
	"time"

	"github.com/CCoupel/GhostDrive/internal/types"
	"github.com/CCoupel/GhostDrive/plugins"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// ─── GetFileState / SetFileState ─────────────────────────────────────────────

// TestEngineGetSetFileState_Unknown verifies the zero-value behaviour:
// a path that was never stored returns FileStateUnknown.
func TestEngineGetSetFileState_Unknown(t *testing.T) {
	engine, _ := newTestEngine(t, newMockBackend(), t.TempDir())
	state := engine.GetFileState("/some/path/not/stored")
	assert.Equal(t, types.FileStateUnknown, state)
}

// TestEngineSetFileState_StoreAndRetrieve verifies all public constants.
func TestEngineSetFileState_StoreAndRetrieve(t *testing.T) {
	engine, _ := newTestEngine(t, newMockBackend(), t.TempDir())
	const p = "/local/file.txt"

	cases := []types.FileState{
		types.FileStateLocal,
		types.FileStatePending,
		types.FileStateUploading,
		types.FileStateSynced,
		types.FileStateConflict,
		types.FileStateError,
		types.FileStateExcluded,
	}
	for _, state := range cases {
		engine.SetFileState(p, state)
		got := engine.GetFileState(p)
		assert.Equal(t, state, got, "expected state %q, got %q", state, got)
	}
}

// TestEngineSetFileState_UnknownDeletesEntry verifies that storing
// FileStateUnknown removes the entry (LoadAndDelete behaviour of sync.Map).
func TestEngineSetFileState_UnknownDeletesEntry(t *testing.T) {
	engine, _ := newTestEngine(t, newMockBackend(), t.TempDir())
	const p = "/local/file.txt"

	engine.SetFileState(p, types.FileStateSynced)
	require.Equal(t, types.FileStateSynced, engine.GetFileState(p))

	engine.SetFileState(p, types.FileStateUnknown)
	assert.Equal(t, types.FileStateUnknown, engine.GetFileState(p), "setting Unknown should remove the entry")
}

// TestEngineGetSetFileState_Concurrent verifies that concurrent goroutines can
// call GetFileState and SetFileState without data races.
// Run with: go test -race ./internal/sync/...
func TestEngineGetSetFileState_Concurrent(t *testing.T) {
	engine, _ := newTestEngine(t, newMockBackend(), t.TempDir())

	const (
		writers = 8
		readers = 8
		iters   = 200
	)

	paths := []string{"/a/b/c.txt", "/x/y/z.txt", "/tmp/file.bin"}
	states := []types.FileState{
		types.FileStateLocal,
		types.FileStatePending,
		types.FileStateUploading,
		types.FileStateSynced,
	}

	var wg sync.WaitGroup

	// Concurrent writers.
	for i := range writers {
		wg.Add(1)
		go func(id int) {
			defer wg.Done()
			p := paths[id%len(paths)]
			s := states[id%len(states)]
			for j := range iters {
				engine.SetFileState(fmt.Sprintf("%s.%d", p, j%5), s)
			}
		}(i)
	}

	// Concurrent readers (interleaved with writers).
	for i := range readers {
		wg.Add(1)
		go func(id int) {
			defer wg.Done()
			p := paths[id%len(paths)]
			for j := range iters {
				_ = engine.GetFileState(fmt.Sprintf("%s.%d", p, j%5))
			}
		}(i)
	}

	done := make(chan struct{})
	go func() {
		wg.Wait()
		close(done)
	}()

	select {
	case <-done:
		// pass
	case <-time.After(10 * time.Second):
		t.Fatal("concurrent GetFileState/SetFileState deadlocked or timed out")
	}
}

// ─── makeStateUpdater ─────────────────────────────────────────────────────────

// TestEngineMakeStateUpdater_EmitsFileStateChanged verifies that the callback
// produced by makeStateUpdater:
//   - stores the state in fileStates
//   - emits "sync:file-state-changed" with correct payload
func TestEngineMakeStateUpdater_EmitsFileStateChanged(t *testing.T) {
	engine, emitter := newTestEngine(t, newMockBackend(), t.TempDir())
	updater := engine.makeStateUpdater()

	const p = "/local/doc.txt"
	updater(p, types.FileStateUploading)

	// State must be stored.
	assert.Equal(t, types.FileStateUploading, engine.GetFileState(p))

	// Event must have been emitted.
	require.Len(t, emitter.events, 1)
	assert.Equal(t, "sync:file-state-changed", emitter.events[0].Name)
	payload, ok := emitter.events[0].Data.(map[string]string)
	require.True(t, ok, "event data must be map[string]string")
	assert.Equal(t, p, payload["localPath"])
	assert.Equal(t, string(types.FileStateUploading), payload["state"])
}

// TestEngineMakeStateUpdater_TransitionUSE verifies the expected sequence of
// transitions U→S→E as generated by a stateUpdater workflow.
func TestEngineMakeStateUpdater_TransitionUSE(t *testing.T) {
	engine, emitter := newTestEngine(t, newMockBackend(), t.TempDir())
	updater := engine.makeStateUpdater()

	const p = "/local/doc.txt"

	transitions := []types.FileState{
		types.FileStateUploading,
		types.FileStateSynced,
		types.FileStateError,
	}
	for _, s := range transitions {
		updater(p, s)
	}

	// Final state must be Error.
	assert.Equal(t, types.FileStateError, engine.GetFileState(p))

	// Three events emitted (one per transition).
	assert.Len(t, emitter.events, 3)

	wantStates := []string{"U", "S", "E"}
	for i, ev := range emitter.events {
		payload, _ := ev.Data.(map[string]string)
		assert.Equal(t, wantStates[i], payload["state"],
			"transition %d: wrong state in event", i)
	}
}

// TestEngineMakeStateUpdater_IntentConsumed_OnUSTransition verifies that when
// a file transitions from Uploading → Synced the intent consumer is called
// and the deferred PinFile is invoked asynchronously (#143).
func TestEngineMakeStateUpdater_IntentConsumed_OnUSTransition(t *testing.T) {
	engine, _ := newTestEngine(t, newMockBackend(), t.TempDir())

	const p = "/local/upload.bin"
	const backendID = "backend-42"

	// Simulate a stored intent for this path.
	intentConsumed := make(chan struct{}, 1)
	pinExecuted := make(chan struct{}, 1)

	engine.SetIntentCallbacks(
		func(localPath string) (string, bool, bool) {
			if localPath == p {
				intentConsumed <- struct{}{}
				return backendID, true, true
			}
			return "", false, false
		},
		func(bid, lp string, pin bool) error {
			assert.Equal(t, backendID, bid)
			assert.Equal(t, p, lp)
			assert.True(t, pin)
			pinExecuted <- struct{}{}
			return nil
		},
	)

	updater := engine.makeStateUpdater()

	// First set to Uploading so prev == U.
	engine.SetFileState(p, types.FileStateUploading)
	// Now transition U→S.
	updater(p, types.FileStateSynced)

	// Intent and PinFile must be called asynchronously — give them a moment.
	select {
	case <-intentConsumed:
	case <-time.After(2 * time.Second):
		t.Fatal("intent consumer not called after U→S transition")
	}
	select {
	case <-pinExecuted:
	case <-time.After(2 * time.Second):
		t.Fatal("pinFile not called after intent consumed")
	}
}

// ─── L-guard: handleLocalEvent ─────────────────────────────────────────────

// TestEngineHandleLocalEvent_LGuard_SkipsRemoteDelete verifies that
// deleting a file marked FileStateLocal does NOT trigger a remote ActionDelete
// (i.e. the mockBackend.Delete should not be called for local-only files, #141).
func TestEngineHandleLocalEvent_LGuard_SkipsRemoteDelete(t *testing.T) {
	tmp := t.TempDir()
	backend := newMockBackend()
	engine, _ := newTestEngine(t, backend, tmp)

	// Pre-create a local file and mark it L.
	localFile := filepath.Join(tmp, "local_only.txt")
	require.NoError(t, os.WriteFile(localFile, []byte("local only"), 0644))
	engine.SetFileState(localFile, types.FileStateLocal)

	// Seed the backend with a different remote file to detect spurious deletes.
	backend.addRemoteFile("/remote/other.txt", 10, time.Now())

	// Fire FileEventDeleted for the local-only file.
	ctx := context.Background()
	err := engine.handleLocalEvent(ctx, plugins.FileEvent{
		Type:   plugins.FileEventDeleted,
		Path:   "local_only.txt",
		Source: "local",
	})
	require.NoError(t, err, "L-guard must not return an error")

	// State must be cleared.
	assert.Equal(t, types.FileStateUnknown, engine.GetFileState(localFile),
		"L-guard must delete the fileStates entry")

	// The only remote file (other.txt) must still be present — Delete was not called.
	_, ok := backend.files["/remote/other.txt"]
	assert.True(t, ok, "remote file for other.txt must not be deleted by L-guard")
}

// TestEngineHandleLocalEvent_Delete_SyncedFile_DispatchesRemoteDelete verifies
// the positive path: deleting a Synced file DOES dispatch ActionDelete.
func TestEngineHandleLocalEvent_Delete_SyncedFile_DispatchesRemoteDelete(t *testing.T) {
	tmp := t.TempDir()
	backend := newMockBackend()
	engine, _ := newTestEngine(t, backend, tmp)

	// Seed a remote file that matches the local path.
	backend.addRemoteFile("/remote/synced.txt", 5, time.Now())
	localPath := filepath.Join(tmp, "synced.txt")
	engine.SetFileState(localPath, types.FileStateSynced)

	ctx := context.Background()
	err := engine.handleLocalEvent(ctx, plugins.FileEvent{
		Type:   plugins.FileEventDeleted,
		Path:   "synced.txt",
		Source: "local",
	})
	require.NoError(t, err)

	// Remote file must have been deleted.
	_, ok := backend.files["/remote/synced.txt"]
	assert.False(t, ok, "ActionDelete must have been dispatched for a Synced file")
}

// TestEngineMakeStateUpdater_NoDowngradeSyncedToLocal verifies that once a file
// reaches FileStateSynced, the state updater DOES NOT allow a downgrade to
// FileStateLocal (#149 fix 3).
//
// Root cause: the reconciler may race with a concurrent upload and classify an
// already-uploaded file as local-only (because its remote-listing snapshot
// predates the upload completion). Allowing S→L would cause ActionDelete to be
// silently skipped (via the #141 guard), making deleted files reappear after the
// next reconciliation.
func TestEngineMakeStateUpdater_NoDowngradeSyncedToLocal(t *testing.T) {
	engine, emitter := newTestEngine(t, newMockBackend(), t.TempDir())
	updater := engine.makeStateUpdater()

	const p = "/local/guarded.txt"

	// Transition Unknown → Synced.
	updater(p, types.FileStateSynced)
	require.Equal(t, types.FileStateSynced, engine.GetFileState(p),
		"precondition: file must be Synced before the guard is tested")

	// Attempt reconciler-style S → L downgrade.
	updater(p, types.FileStateLocal)

	// State must remain Synced — the guard must block the downgrade.
	assert.Equal(t, types.FileStateSynced, engine.GetFileState(p),
		"#149: S→L downgrade must be blocked; state must remain Synced")

	// Exactly one sync:file-state-changed event: Unknown→Synced.
	// The blocked S→L transition must NOT emit a second event.
	stateEvents := 0
	for _, ev := range emitter.events {
		if ev.Name == "sync:file-state-changed" {
			stateEvents++
		}
	}
	assert.Equal(t, 1, stateEvents,
		"#149: exactly one state event expected (Unknown→Synced); blocked S→L must not emit")
}

// TestEngineHandleLocalEvent_Renamed_EmptyOldPath_Ignored verifies that an
// incomplete rename event (OldPath == "") is silently ignored (#139).
func TestEngineHandleLocalEvent_Renamed_EmptyOldPath_Ignored(t *testing.T) {
	tmp := t.TempDir()
	backend := newMockBackend()
	engine, _ := newTestEngine(t, backend, tmp)

	ctx := context.Background()
	err := engine.handleLocalEvent(ctx, plugins.FileEvent{
		Type:   plugins.FileEventRenamed,
		Path:   "newname.txt",
		OldPath: "",
		Source: "local",
	})
	require.NoError(t, err, "incomplete rename must be ignored without error")
}
