// Auto-generated by Wails v2 — DO NOT MODIFY

export function EventsOn(eventName, callback) {
  return window['runtime']['EventsOn'](eventName, callback);
}

export function EventsOnce(eventName, callback) {
  return window['runtime']['EventsOnce'](eventName, callback);
}

export function EventsOff(...eventNames) {
  return window['runtime']['EventsOff'](...eventNames);
}

export function EventsEmit(eventName, ...data) {
  return window['runtime']['EventsEmit'](eventName, ...data);
}

export function WindowMinimise() {
  return window['runtime']['WindowMinimise']();
}

export function WindowHide() {
  return window['runtime']['WindowHide']();
}

export function WindowShow() {
  return window['runtime']['WindowShow']();
}

export function Quit() {
  return window['runtime']['Quit']();
}
