// Auto-generated by Wails v2 — DO NOT MODIFY

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function SaveConfig(config) {
  return window['go']['main']['App']['SaveConfig'](config);
}

export function AddBackend(config) {
  return window['go']['main']['App']['AddBackend'](config);
}

export function RemoveBackend(backendID) {
  return window['go']['main']['App']['RemoveBackend'](backendID);
}

export function TestBackendConnection(config) {
  return window['go']['main']['App']['TestBackendConnection'](config);
}

export function GetSyncState() {
  return window['go']['main']['App']['GetSyncState']();
}

export function StartSync(backendID) {
  return window['go']['main']['App']['StartSync'](backendID);
}

export function StopSync(backendID) {
  return window['go']['main']['App']['StopSync'](backendID);
}

export function PauseSync(backendID) {
  return window['go']['main']['App']['PauseSync'](backendID);
}

export function ForceSync(backendID) {
  return window['go']['main']['App']['ForceSync'](backendID);
}

export function ListFiles(backendID, path) {
  return window['go']['main']['App']['ListFiles'](backendID, path);
}

export function DownloadFile(backendID, remotePath) {
  return window['go']['main']['App']['DownloadFile'](backendID, remotePath);
}

export function OpenSyncFolder(backendID) {
  return window['go']['main']['App']['OpenSyncFolder'](backendID);
}

export function GetCacheStats() {
  return window['go']['main']['App']['GetCacheStats']();
}

export function ClearCache() {
  return window['go']['main']['App']['ClearCache']();
}

export function GetBackendStatuses() {
  return window['go']['main']['App']['GetBackendStatuses']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}
